# Generated by Django 5.2.8 on 2025-12-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('studentid', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=8, null=True)),
                ('department', models.CharField(blank=True, choices=[('cs', 'computerscience'), ('el', 'electronics'), ('mc', 'machanical'), ('cs', 'computerscience'), ('cv', 'civil')], max_length=2, null=True)),
                ('phone', models.IntegerField()),
                ('semester', models.CharField(blank=True, choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8')], max_length=1, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
