# Generated by Django 5.2.8 on 2026-01-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentleaveapp', '0003_leaveapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='status',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
