# Generated by Django 5.2.8 on 2026-01-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentleaveapp', '0004_remove_leaveapplication_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
