# Generated by Django 5.2.1 on 2026-01-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentleaveapp', '0005_leaveapplication_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='admin_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
