# Generated by Django 5.2.1 on 2026-01-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentleaveapp', '0006_leaveapplication_admin_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_count',
            field=models.IntegerField(default=0),
        ),
    ]
