# Generated by Django 5.2.8 on 2026-01-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentleaveapp', '0007_leaveapplication_leave_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, choices=[('FT', 'Fashion Technology'), ('SD', 'Software Development'), ('MM', 'MultiMedia')], max_length=2, null=True),
        ),
    ]
