# Generated by Django 5.2.8 on 2026-01-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentleaveapp', '0008_alter_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='leave_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
