# Generated by Django 5.2.8 on 2026-01-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentleaveapp', '0009_student_leave_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_leave_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
