# Generated by Django 5.2.8 on 2026-01-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentleaveapp', '0010_student_last_leave_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, choices=[('FT', 'Fashion Technology'), ('SD', 'Software Development'), ('MM', 'MultiMedia'), ('AT', 'Accounting and taxation')], max_length=2, null=True),
        ),
    ]
