# Generated by Django 5.2.8 on 2026-01-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentleaveapp', '0011_alter_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='dept',
            field=models.CharField(blank=True, null=True),
        ),
    ]
