# Generated by Django 5.2.8 on 2026-01-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentleaveapp', '0012_leaveapplication_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, choices=[('Fashion Technology', 'Fashion Technology'), ('Software Development', 'Software Development'), ('MultiMedia', 'MultiMedia'), ('Accounting and Taxation', 'Accounting and taxation')], max_length=50, null=True),
        ),
    ]
