# Generated by Django 5.2.8 on 2026-01-25 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentleaveapp', '0013_alter_student_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedCerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificate/')),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentleaveapp.student')),
            ],
        ),
    ]
