# Generated by Django 5.2.8 on 2026-01-25 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentleaveapp', '0014_medcerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medcerts',
            name='leave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentleaveapp.leaveapplication'),
        ),
    ]
