# Generated by Django 5.2.8 on 2026-01-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentleaveapp', '0015_alter_medcerts_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='medsub',
            field=models.BooleanField(default=False),
        ),
    ]
