# Generated by Django 5.1.5 on 2026-03-08 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentleaveapp', '0016_leaveapplication_medsub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='dept',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentleaveapp.leaveapplication')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentleaveapp.student')),
            ],
        ),
    ]
