# Generated by Django 5.1.5 on 2026-03-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentleaveapp', '0017_alter_leaveapplication_dept_alter_student_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notifications',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notifications',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
